name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📗 Profile
        uses: lowlighter/metrics@master
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, repositories
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, dockerfile, makefile, cmake, shell, gnuplot, glsl, objective-c, jupyter notebook
          config_order: base.header, base.activity, languages, base.repositories
